grafana:
  persistence:
    enabled: true
    type: pvc
    size: 2Gi

  grafana.ini:
    auth.anonymous:
      enabled: true
      org_name: Main Org.
      org_role: Viewer
    auth:
      disable_login_form: false
prometheus:
  prometheusSpec:
    retention: 24h
    retentionSize: "5GB"