---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-credentials
  namespace: default
spec:
  encryptedData:
    password: AgA7dqbLaAWd9MUV682gfh13YTzWs0Yr4/ipdQfTHqMLSKTkRmINvJEVAjm1Tgv309Wb/CbJNW2LFOD41/sbWGII6Zb3fkil2oUH4X7cL9ClJt9HfWQzG1UmzKaNmGCLIu3bOb3DFyaLj3VXSJM7xBr3sfKXquuXsm29YvmqdIzWlm+ZoQ2yGwO1nkVupGWINZVrhENYegyeh8DASMtxHLr48YRKvbzXdRPvAiu0TC+adAFSWNW/bmppln7zQAVgsdlidGBWsigYDB7IGPacJmYi06EzNdX8/R/ApFeAMHe9BYWs3rBuW2Yc6+zpLVOtA2RoaJ4uEdVnlMJzQja16JAQ5xAuIP8qvNHVyEFBNlHvarCRiwblglhRP6EkRP7+wTKBLJGphrddMFmALYuEjbOcXG1TGQiPzq3eE20Fbm+3ztFO+gZFHWz6xeQpWnVUP1wtDK2qZUFWdoAO5W1ghRgI6xJylPXwfYsSVoFqatr5giunqyKDVVPvK/H5QYXm9Zh5z5bOgPLgd9XFzRGc+27ekvP+nPXsTdKQN7xk8K4u7dGmXesArNoR618vrLALSAqjD0aepWtWYIPpaypF6pN8ynrub+hcp6CNGFpZmIXYqfKV6MSySL6wyG5DqK5NNmi7aDbO+NlCuL9+bEtbueG3RLx4kW+V5FwcHJ8ccFMLZUIO+yPIYdJshGugwhFMGZm2c9vZG2CG67DhCQ==
    username: AgAk4lhQmoU34Cii9QPHaGt/TAM/Q9H2vjR9Z/sPFqYh58Et37qDh9cwOk+i8TR28PLQdc/yf4UqJfwGDzVCGRvJKNyp+rxcmntTqbOdSOQ34ipq6YDZMBAFIf+PLlAuLC3cyNb+24/b4iG76VYwH0f5fsiW/7ACDrsYSIGqTsxVvqXLm73YA1C2YvMkMLAfFwaB1oS0UHjwGxdxRBD6V/tG9t1vyHsMkXZaVPV2H6dpwEkuLjcTV2kvWiBUhEFeYPIkBZSitPdeG05PewnKlpus1qMaG8YCGNNYBC3Sx1UR1JIMhB73oX443rYhW3MwDZHcMNw8/Nj+glusqBkOvf4ObBWKFJspSKdCye+tNvtt+YeAKsJtPg1soj4bEdxoa0+UXai17voJOuyDH+Ix7hypd7ARzhhfYhtgNeiTTp/iAYaR3o07KHdI+vpYLEUeGdbyJOoY9axN9KdJ0aWU8Ibz5KeltTDtJ3O6USjALpg74cqThSy665Su5cFXyj7L1S+Fqzb2sIpALqqQVJfSySjIHKd9zb5xoUbWOYBBHxVYS+kx8/RLiLhCKx7cLRhrwPZXaOr9d4loYqD3XyBarYJKPBEDSkrjbvAXrPrAPe6RmRoojBft/TbTJDfU1l6ALkcnvFEe61lZUezu6EwyqxMlVvofPbAsH/AgB09bv6y47n+JvRngDodzCvMWAuk0qWyR6ATMPA==
  template:
    metadata:
      name: nextcloud-credentials
      namespace: default
