apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: portfolio-demo-monitor
  namespace: default
  labels:
    release: monitoring-stack
spec:
  selector:
    matchLabels:
      app: portfolio-demo
  endpoints:
  - port: http            
    path: /metrics        
    interval: 15s